name: Lint

on:
  pull_request:
    branches: [ master ]

jobs:
  validate-xosc:
    env:
      SCEN_DIR: ./Scenarios 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        xml-file: [ ./Scenarios/'*.xosc' ]
        #xml-file: [ ./Scenarios/ALKS_MASTER_Scenario_TEMPLATE.xosc, ./Scenarios/ALKS_Scenario_1_1_FreeDriving_TEMPLATE.xosc ]
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Lint MASTER Scenario
      uses: ChristophWurst/xmllint-action@v1
      with:
        xml-file: ${{ matrix.xml-file }}
        xml-schema-file: ./.github/workflows/OpenSCENARIO.xsd
