name: Validate-OpenX-files

on:
  pull_request:
    branches: [ master ]

jobs:
  validate-openx-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Validate all scenarios
        uses: ChristophWurst/xmllint-action@v1
        with:
          xml-file: ./Scenarios/ALKS_Scenario_1_1_FreeDriving_TEMPLATE.xosc ./Scenarios/ALKS_Scenario_1_2_SwervingLeadVehicle_TEMPLATE.xosc ./Scenarios/ALKS_Scenario_1_3_SwervingSideVehicle_TEMPLATE.xosc ./Scenarios/ALKS_Scenario_2_1_FullyBlockingTarget_TEMPLATE.xosc ./Scenarios/ALKS_Scenario_2_2_PartiallyBlockingTarget_TEMPLATE.xosc ./Scenarios/ALKS_Scenario_2_3_CrossingPedestrian_TEMPLATE.xosc ./Scenarios/ALKS_Scenario_2_4_MultipleBlockingTargets_TEMPLATE.xosc ./Scenarios/ALKS_Scenario_3_1_FollowLeadVehicleComfortable_TEMPLATE.xosc ./Scenarios/ALKS_Scenario_3_2_FollowLeadVehicleEmergencyBrake_TEMPLATE.xosc ./Scenarios/ALKS_Scenario_4_1_CutInNoCollision_TEMPLATE.xosc ./Scenarios/ALKS_Scenario_4_1_CutInNoCollision_TEMPLATE_esmini.xosc ./Scenarios/ALKS_Scenario_4_2_CutInUnavoidableCollision_TEMPLATE.xosc ./Scenarios/ALKS_Scenario_4_2_CutInUnavoidableCollision_TEMPLATE_esmini.xosc ./Scenarios/ALKS_Scenario_5_1_CutOutFullyBlocking_TEMPLATE.xosc ./Scenarios/ALKS_Scenario_5_2_CutOutMultipleBlockingTargets_TEMPLATE.xosc ./Scenarios/ALKS_Scenario_6_1_ForwardDetectionRange_TEMPLATE.xosc ./Scenarios/ALKS_Scenario_6_2_LateralDetectionRange_TEMPLATE.xosc ./Catalogs/Controllers/ControllerCatalog.xosc ./Catalogs/MiscObjects/MiscObjectCatalog.xosc ./Catalogs/Vehicles/VehicleCatalog.xosc ./Catalogs/Pedestrians/PedestrianCatalog.xosc
          xml-schema-file: ./.github/workflows/OpenSCENARIO.xsd
      - name: Validate all maps
        uses: ChristophWurst/xmllint-action@v1
        with:
          xml-file: ./Scenarios/ALKS_Road.xodr ./Scenarios/ALKS_Road_Different_Curvatures.xodr
          xml-schema-file: ./.github/workflows/opendrive_16_core.xsd
