name: Lint

on:
  pull_request:
    branches: [ master ]

jobs:
  validate-xosc:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Lint MASTER Scenario
      uses: ChristophWurst/xmllint-action@v1
      with:
        xml-file: ./Scenarios/ALKS_MASTER_Scenario_TEMPLATE.xosc
        xml-schema-file: ./.github/workflows/OpenSCENARIO.xsd
